In [93]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [94]:
df1= pd.read_csv('tuyensinh10(1).csv', encoding='utf-8')

In [95]:
df2= pd.read_csv('tuyensinh10(2).csv', encoding='utf-8')

In [96]:
df= pd.concat([df1, df2], ignore_index=True)
df

,SBD,Họ và tên,Giới tính,Ngày sinh,Trường TH/THCS,Quận/Huyện/TX,Nguyện vọng 1,Nguyện vọng 2,Nguyện vọng 3,Điểm Toán,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,100001,TRẦN KHÁNH AN,x,08/08/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,NaN,"4,50",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100002,LÊ ĐỨC ANH,NaN,21/11/2010,THCS Phan Thế Phương,Huyện Quảng Điền,THPT Tố Hữu,NaN,NaN,"0,50",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100003,HOÀNG NHƯ ANH,NaN,22/10/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,NaN,"1,25",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100004,ĐINH THỊ NGỌC ANH,x,02/08/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,NaN,"1,25",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100005,TRẦN THỊ QUỲNH ANH,x,13/10/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,NaN,"1,75",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11124,90267,PHAN THỊ BẢO VY,x,27/02/2010,THCS Đặng Tất,Huyện Quảng Điền,THPT Hoá Châu,THPT Tố Hữu,NaN,"4,25",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11125,90268,TRẦN THỊ THẢO VY,x,5/8/2010,THCS Đặng Tất,Huyện Quảng Điền,THPT Hoá Châu,THPT Tố Hữu,NaN,"2,50",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11126,90269,TRẦN THỊ THẢO VY,x,21/03/2010,THCS Trần Thúc Nhẫn,Huyện Quảng Điền,THPT Đặng Huy Trứ,THPT Nguyễn Chí Thanh,THPT Hoá Châu,"6,00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11127,90270,ĐỖ TUẤN VỸ,NaN,27/02/2010,THCS Trần Thúc Nhẫn,Huyện Quảng Điền,THPT Đặng Huy Trứ,THPT Hoá Châu,NaN,"1,00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11128,90271,BÙI HOÀNG BẢO YẾN,x,22/04/2010,THCS Nguyễn Hữu Dật,Huyện Quảng Điền,THPT Hoá Châu,THPT Nguyễn Chí Thanh,THPT Hương Vinh,"4,75",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Kiểm tra và xóa các dòng giống hệt nhau (giữ lại bản ghi thứ nhất)

In [97]:

duplicated_rows = df[df.duplicated()]
print(f"Số dòng trùng lặp hoàn toàn: {duplicated_rows.shape[0]}")
df = df.drop_duplicates()

Số dòng trùng lặp hoàn toàn: 174

các tên cột  viết thường, thay thế khoảng trắng

In [98]:
from unidecode import unidecode

df.columns = [unidecode(col).lower().replace(" ", "_") for col in df.columns]

In [99]:
df.head()

,sbd,ho_va_ten,gioi_tinh,ngay_sinh,truong_th/thcs,quan/huyen/tx,nguyen_vong_1,nguyen_vong_2,nguyen_vong_3,diem_toan,...,unnamed:_17,unnamed:_18,unnamed:_19,unnamed:_20,unnamed:_21,unnamed:_22,unnamed:_23,unnamed:_24,unnamed:_25,unnamed:_26
0,100001,TRẦN KHÁNH AN,x,08/08/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,NaN,"4,50",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100002,LÊ ĐỨC ANH,NaN,21/11/2010,THCS Phan Thế Phương,Huyện Quảng Điền,THPT Tố Hữu,NaN,NaN,"0,50",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100003,HOÀNG NHƯ ANH,NaN,22/10/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,NaN,"1,25",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100004,ĐINH THỊ NGỌC ANH,x,02/08/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,NaN,"1,25",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100005,TRẦN THỊ QUỲNH ANH,x,13/10/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,NaN,"1,75",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Kiểm tra dữ liệu thiếu

In [100]:
df.isnull().sum()

sbd                            0
ho_va_ten                      0
gioi_tinh                   5460
ngay_sinh                      0
truong_th/thcs                 1
quan/huyen/tx                  1
nguyen_vong_1                 70
nguyen_vong_2                629
nguyen_vong_3               3181
diem_toan                    207
diem_ngu_van/tieng_viet      205
diem_ngoai_ngu               206
tong_xet_pho_thong/ntp       208
ket_qua                        1
unnamed:_14                10954
unnamed:_15                10954
unnamed:_16                10954
unnamed:_17                10954
unnamed:_18                10954
unnamed:_19                10954
unnamed:_20                10954
unnamed:_21                10955
unnamed:_22                10954
unnamed:_23                10954
unnamed:_24                10954
unnamed:_25                10954
unnamed:_26                10954
dtype: int64

Xử lý thiếu dữ liệu ở cột giới tính

In [101]:
df['gioi_tinh'] = df['gioi_tinh'].replace('x', 'Nữ')
df['gioi_tinh'] = df['gioi_tinh'].replace('', 'Nam')  # thay chuỗi rỗng 
df['gioi_tinh'] = df['gioi_tinh'].fillna('Nam')       # thay NaN bằng Nam

C:\Users\Asus-FPT\AppData\Local\Temp\ipykernel_14380\2252170355.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gioi_tinh'] = df['gioi_tinh'].replace('x', 'Nữ')
C:\Users\Asus-FPT\AppData\Local\Temp\ipykernel_14380\2252170355.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gioi_tinh'] = df['gioi_tinh'].replace('', 'Nam')  # thay chuỗi rỗng
C:\Users\Asus-FPT\AppData\Local\Temp\ipykernel_14380\2252170355.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gioi_tinh'] = df['gioi_tinh'].fillna('Nam')       # thay NaN bằng Nam

Xóa các cột dữ liệu không có ý nghĩa

In [102]:
df=df.drop(columns=['unnamed:_14', 'unnamed:_15', 'unnamed:_16', 'unnamed:_17', 
'unnamed:_18', 'unnamed:_19', 'unnamed:_20', 'unnamed:_21', 'unnamed:_22',
 'unnamed:_23', 'unnamed:_24', 'unnamed:_25', 'unnamed:_26'])

In [103]:
df.head()

,sbd,ho_va_ten,gioi_tinh,ngay_sinh,truong_th/thcs,quan/huyen/tx,nguyen_vong_1,nguyen_vong_2,nguyen_vong_3,diem_toan,diem_ngu_van/tieng_viet,diem_ngoai_ngu,tong_xet_pho_thong/ntp,ket_qua
0,100001,TRẦN KHÁNH AN,Nữ,08/08/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,NaN,"4,50","5,25","6,4","26,15",Đậu Trường THPT Tố Hữu
1,100002,LÊ ĐỨC ANH,Nam,21/11/2010,THCS Phan Thế Phương,Huyện Quảng Điền,THPT Tố Hữu,NaN,NaN,"0,50","1,00","2,8","8,3",Đậu Trường THPT Tố Hữu
2,100003,HOÀNG NHƯ ANH,Nam,22/10/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,NaN,"1,25","1,50","2,4","10,15",Đậu Trường THPT Tố Hữu
3,100004,ĐINH THỊ NGỌC ANH,Nữ,02/08/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,NaN,"1,25","3,25","2,8","14,3",Đậu Trường THPT Tố Hữu
4,100005,TRẦN THỊ QUỲNH ANH,Nữ,13/10/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,NaN,"1,75","2,50","3,2","15,45",Đậu Trường THPT Tố Hữu

Chuyển đổi dữ liệu (từ string > float)

In [104]:
cols_diem = ['diem_toan', 'diem_ngu_van/tieng_viet', 'diem_ngoai_ngu', 'tong_xet_pho_thong/ntp']

for col in cols_diem:
    df[col] = df[col].astype(str).str.replace(',', '.', regex=False)
    df[col] = pd.to_numeric(df[col], errors='coerce')  # chuyển sang float, lỗi thì thành NaN

Các ô trống (không có điểm): không tham gia thi môn đó.

In [105]:
df['diem_toan'] = pd.to_numeric(df['diem_toan'], errors='coerce')  # 'vắng' hay '--' thành NaN
df['diem_ngoai_ngu'] = pd.to_numeric(df['diem_ngoai_ngu'], errors='coerce')  # 'vắng' hay '--' thành NaN
df['diem_ngu_van/tieng_viet'] = pd.to_numeric(df['diem_ngu_van/tieng_viet'], errors='coerce')  # 'vắng' hay '--' thành NaN
# df['diem_toan'] = df['diem_toan'].fillna(0)
# df['diem_ngoai_ngu'] = df['diem_ngoai_ngu'].fillna(0)
# df['diem_ngu_van/tieng_viet'] = df['diem_ngu_van/tieng_viet'].fillna(0)
# df['tong_xet_pho_thong/ntp'] = df['tong_xet_pho_thong/ntp'].fillna(0)

In [106]:
cols_nguyen_vong= ['nguyen_vong_1', 'nguyen_vong_2', 'nguyen_vong_3']
for col in cols_nguyen_vong:
    df[col] = df[col].str.strip()  # loại bỏ khoảng trắng đầu cuối
    df[col]=df[col].fillna('Không đăng ký')

In [107]:

df.head(3)

,sbd,ho_va_ten,gioi_tinh,ngay_sinh,truong_th/thcs,quan/huyen/tx,nguyen_vong_1,nguyen_vong_2,nguyen_vong_3,diem_toan,diem_ngu_van/tieng_viet,diem_ngoai_ngu,tong_xet_pho_thong/ntp,ket_qua
0,100001,TRẦN KHÁNH AN,Nữ,08/08/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,Không đăng ký,4.50,5.25,6.4,26.15,Đậu Trường THPT Tố Hữu
1,100002,LÊ ĐỨC ANH,Nam,21/11/2010,THCS Phan Thế Phương,Huyện Quảng Điền,THPT Tố Hữu,Không đăng ký,Không đăng ký,0.50,1.00,2.8,8.30,Đậu Trường THPT Tố Hữu
2,100003,HOÀNG NHƯ ANH,Nam,22/10/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,Không đăng ký,1.25,1.50,2.4,10.15,Đậu Trường THPT Tố Hữu

Thêm cột điểm THCS

In [108]:
# df['diem_thcs']=(df['tong_xet_pho_thong/ntp']- df['diem_ngoai_ngu']- df['diem_ngu_van/tieng_viet']-df['diem_toan'])
df['diem_thcs'] = (
    df['tong_xet_pho_thong/ntp']
    - df['diem_ngoai_ngu']
    - df['diem_ngu_van/tieng_viet']
    - df['diem_toan']
).clip(upper=10)

một số hàng ở cột tổng xét khi crawl đã đọc sai khi trả về 0 điểm >> Tính toán lại

In [109]:
# df['tong_xet_pho_thong/ntp'] = (df['diem_ngoai_ngu'] + df['diem_ngu_van/tieng_viet']+ df['diem_toan'] + df['diem_thcs'])

In [110]:
df['diem_thcs'] = df['diem_thcs'].fillna(0)

In [111]:
df.head()

,sbd,ho_va_ten,gioi_tinh,ngay_sinh,truong_th/thcs,quan/huyen/tx,nguyen_vong_1,nguyen_vong_2,nguyen_vong_3,diem_toan,diem_ngu_van/tieng_viet,diem_ngoai_ngu,tong_xet_pho_thong/ntp,ket_qua,diem_thcs
0,100001,TRẦN KHÁNH AN,Nữ,08/08/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,Không đăng ký,4.50,5.25,6.4,26.15,Đậu Trường THPT Tố Hữu,10.0
1,100002,LÊ ĐỨC ANH,Nam,21/11/2010,THCS Phan Thế Phương,Huyện Quảng Điền,THPT Tố Hữu,Không đăng ký,Không đăng ký,0.50,1.00,2.8,8.30,Đậu Trường THPT Tố Hữu,4.0
2,100003,HOÀNG NHƯ ANH,Nam,22/10/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,Không đăng ký,1.25,1.50,2.4,10.15,Đậu Trường THPT Tố Hữu,5.0
3,100004,ĐINH THỊ NGỌC ANH,Nữ,02/08/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,Không đăng ký,1.25,3.25,2.8,14.30,Đậu Trường THPT Tố Hữu,7.0
4,100005,TRẦN THỊ QUỲNH ANH,Nữ,13/10/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,Không đăng ký,1.75,2.50,3.2,15.45,Đậu Trường THPT Tố Hữu,8.0

Sắp xếp vị trí các cột hợp lý

In [112]:
thcs_col=df.pop('diem_thcs')
df.insert(12,'diem_thcs',thcs_col)

In [113]:
df.head()

,sbd,ho_va_ten,gioi_tinh,ngay_sinh,truong_th/thcs,quan/huyen/tx,nguyen_vong_1,nguyen_vong_2,nguyen_vong_3,diem_toan,diem_ngu_van/tieng_viet,diem_ngoai_ngu,diem_thcs,tong_xet_pho_thong/ntp,ket_qua
0,100001,TRẦN KHÁNH AN,Nữ,08/08/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,Không đăng ký,4.50,5.25,6.4,10.0,26.15,Đậu Trường THPT Tố Hữu
1,100002,LÊ ĐỨC ANH,Nam,21/11/2010,THCS Phan Thế Phương,Huyện Quảng Điền,THPT Tố Hữu,Không đăng ký,Không đăng ký,0.50,1.00,2.8,4.0,8.30,Đậu Trường THPT Tố Hữu
2,100003,HOÀNG NHƯ ANH,Nam,22/10/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,Không đăng ký,1.25,1.50,2.4,5.0,10.15,Đậu Trường THPT Tố Hữu
3,100004,ĐINH THỊ NGỌC ANH,Nữ,02/08/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,Không đăng ký,1.25,3.25,2.8,7.0,14.30,Đậu Trường THPT Tố Hữu
4,100005,TRẦN THỊ QUỲNH ANH,Nữ,13/10/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,Không đăng ký,1.75,2.50,3.2,8.0,15.45,Đậu Trường THPT Tố Hữu

Xử lý về trường chuyên
........................

In [114]:
import pandas as pd
import re

def chuan_hoa_ket_qua(text):
    if pd.isna(text):
        return text
    text = text.strip()
    if text.lower().startswith("đậu chuyên"):
        return text.replace("Đậu ", "")
    elif text.lower().startswith("đậu trường"):
        return re.sub(r"^Đậu Trường ", "", text)
    else:
        return text

df['ket_qua'] = df['ket_qua'].apply(chuan_hoa_ket_qua)

In [115]:
df.head()

,sbd,ho_va_ten,gioi_tinh,ngay_sinh,truong_th/thcs,quan/huyen/tx,nguyen_vong_1,nguyen_vong_2,nguyen_vong_3,diem_toan,diem_ngu_van/tieng_viet,diem_ngoai_ngu,diem_thcs,tong_xet_pho_thong/ntp,ket_qua
0,100001,TRẦN KHÁNH AN,Nữ,08/08/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,Không đăng ký,4.50,5.25,6.4,10.0,26.15,THPT Tố Hữu
1,100002,LÊ ĐỨC ANH,Nam,21/11/2010,THCS Phan Thế Phương,Huyện Quảng Điền,THPT Tố Hữu,Không đăng ký,Không đăng ký,0.50,1.00,2.8,4.0,8.30,THPT Tố Hữu
2,100003,HOÀNG NHƯ ANH,Nam,22/10/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,Không đăng ký,1.25,1.50,2.4,5.0,10.15,THPT Tố Hữu
3,100004,ĐINH THỊ NGỌC ANH,Nữ,02/08/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,Không đăng ký,1.25,3.25,2.8,7.0,14.30,THPT Tố Hữu
4,100005,TRẦN THỊ QUỲNH ANH,Nữ,13/10/2010,THCS Phạm Quang Ái,Huyện Quảng Điền,THPT Tố Hữu,THPT Hoá Châu,Không đăng ký,1.75,2.50,3.2,8.0,15.45,THPT Tố Hữu

Xử lý dữ liệu trường chuyên
- đậu chuyên > quốc học huế 
- thêm cột ghi chú : chuyên sinh, anh,..

In [116]:
def xu_ly_ket_qua(kq):
    if pd.isna(kq):
        return kq, ''
    kq = kq.strip()
    if kq.lower().startswith('chuyên'):
        return "THPT Quốc học Huế", kq
    return kq, ''      # không phải chuyên thì giữ nguyên

# Áp dụng xử lý với apply theo hàng (axis=1)
df[['ket_qua', 'ghi_chu']] = df['ket_qua'].apply(lambda x: pd.Series(xu_ly_ket_qua(x)))

In [117]:
df.to_csv('tuyensinh10TpHue_cleaned.csv', index=False, encoding='utf-8-sig')

cần xem xét lại cho các trường hợp bỏ thi

tách ngày tháng năm